# Generated by Django 3.0.2 on 2020-02-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200204_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='friends',
            new_name='friend',
        ),
    ]
