# Generated by Django 3.0.2 on 2020-02-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200211_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
